- hosts: all
  become: yes
  tasks: 
  - name: install Apacahe
    include: apache.yml

  - name: install php
    include: php.yml

  - name: install wordpress
    include: wordpress.yml  
    
  - name: install database
    include: db.yml  